### ISSUE TITLE
TypeError: AbqpyCLI.cae() got an unexpected keyword argument 'startup'

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#5579]
Hello everyone, I'm new to Github (first time). 
I'm writting this beacause i think i encontered a bug so i'd like to report it. 
I explain. 

I installed abqpy-2020.7.1 (with abaqus2020 and python 3.10.11). 

when i want to launch my code (code below) i have the following error :
"""
The script will be submitted to Abaqus next and the current Python session will be closed.
Traceback (most recent call last):
  File "worspace_path\test.py", line 1, in <module>
    from abaqus import mdb
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\abaqus\__init__.py", line 7, in <module>
    run(cae=True)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\abqpy\run.py", line 48, in run
    abaqus.cae(filePath, *sys.argv[1:], **config.cae.model_dump())
TypeError: AbqpyCLI.cae() got an unexpected keyword argument 'startup'
"""

I also tried with another version of abqpy-2020 (6.2) and it worked perfectly.

The cae function (from abqpy>cli.py>class AbqpyCLI) has not 'startup' in its keywords (in both versions). So the problem could come from one of the inputs of "abaqus.cae(filePath, *sys.argv[1:], **config.cae.model_dump())" but my knowledge stops here. 

I hope it helps. 
Have a great day, 
Théo

all is executed on an offline windows 10

## Python code : test.py ##
from abaqus import mdb

job = mdb.JobFromInputFile('job_name', 'job_name.inp')
job.submit()
job.waitForCompletion()

## More Things related ##

py file executed in vscode
results from pip list : 
abqpy             2020.7.1
auto-all          1.4.1
fire              0.6.0
pip               23.0.1
pydantic          1.10.14
setuptools        65.6.3
six               1.16.0
termcolor         2.4.0
typeguard         4.1.5
typing_extensions 4.10.0

_Originally posted by @thelongip in https://github.com/haiiliin/abqpy/discussions/146#discussioncomment-8867521_

**Comment by haiiliin** [comment]
The bug is introduced in abqpy version `20**.7.1` (#5492) and will be fixed in `20**.7.2` (#5575)
